"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { CalendarClock, CalendarX2, Check, FileText, Ban, Users, RefreshCw, Loader2 } from "lucide-react"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Skeleton } from "@/components/ui/skeleton"
import { createClient } from "@/lib/supabase/client"
import { useDepartment } from "@/lib/departments/useDepartment"
import {
  currentTerm,
  nextTerm,
  daysToNextTerm,
  isCalendarConfigured,
} from "@/lib/utils/termHelpers"
import { formatDate, daysUntil, getRenewalColorClass } from "@/lib/utils/dateHelpers"
import { cn } from "@/lib/utils"
import type { InvoiceStatus } from "@/types/crm"

/**
 * Term billing — the post-sale page for `term_contract` departments.
 *
 * School Bus is billed once per school term, three terms a year, so the renewal
 * event happens three times rather than once. Rows are generated by
 * `generate_term_billings` from the VERIFIED bus register, grouped here by
 * academic term.
 *
 * THE TERM CALENDAR IS USUALLY EMPTY. Real Kenyan term dates are keyed in by an
 * admin (Sprint D6) and the prompt forbids inventing them, so this page must
 * render a clear "not configured" state rather than throwing or showing a
 * misleading empty table.
 */

interface BillingRow {
  id: string
  lead_id: string
  bus_count: number
  amount_per_bus: number | null
  total_amount: number | null
  currency: string
  due_date: string | null
  invoice_status: InvoiceStatus
  paid_date: string | null
  academic_term_id: string
  lead: { company_name: string | null; full_name: string | null; phone_number: string } | null
  academic_term: { id: string; name: string; start_date: string } | null
}

const STATUS_CLASSES: Record<InvoiceStatus, string> = {
  pending: "bg-slate-100 text-slate-600 border-slate-200",
  invoiced: "bg-sky-100 text-sky-700 border-sky-200",
  paid: "bg-green-100 text-green-700 border-green-200",
  partial: "bg-amber-100 text-amber-700 border-amber-200",
  overdue: "bg-red-100 text-red-700 border-red-200",
  waived: "bg-zinc-100 text-zinc-500 border-zinc-200",
}

function formatKes(amount: number | null, currency = "KES"): string {
  if (amount == null) return "—"
  return `${currency} ${Math.round(amount).toLocaleString("en-KE")}`
}

function schoolName(l: BillingRow["lead"]): string {
  if (!l) return "—"
  return l.company_name ?? l.full_name ?? l.phone_number
}

export function TermBillingShell() {
  const { department, academicTerms } = useDepartment()
  const [rows, setRows] = useState<BillingRow[]>([])
  const [loading, setLoading] = useState(true)
  const [termFilter, setTermFilter] = useState("")
  const [statusFilter, setStatusFilter] = useState("")
  const [generating, setGenerating] = useState(false)

  const calendarReady = isCalendarConfigured(academicTerms)
  const thisTerm = currentTerm(academicTerms)
  const upcoming = nextTerm(academicTerms)
  const daysToNext = daysToNextTerm(academicTerms)

  const load = useCallback(async () => {
    if (!department?.id) {
      setLoading(false)
      return
    }
    const supabase = createClient()
    setLoading(true)
    try {
      const { data, error } = await supabase
        .from("term_billings")
        .select("*, lead:leads(company_name, full_name, phone_number), academic_term:academic_terms(id, name, start_date)")
        .eq("department_id", department.id)
        .order("due_date", { ascending: true, nullsFirst: false })
      if (error) throw error
      setRows((data ?? []) as unknown as BillingRow[])
    } catch (err) {
      console.error("TermBillingShell fetch failed:", err)
      toast.error("Could not load term billing")
    } finally {
      setLoading(false)
    }
  }, [department?.id])

  useEffect(() => {
    void load()
  }, [load])

  const filtered = useMemo(
    () =>
      rows.filter((r) => {
        if (termFilter && r.academic_term_id !== termFilter) return false
        if (statusFilter && r.invoice_status !== statusFilter) return false
        return true
      }),
    [rows, termFilter, statusFilter],
  )

  /** Rows grouped by term, in calendar order. */
  const grouped = useMemo(() => {
    const map = new Map<string, { name: string; start: string; items: BillingRow[] }>()
    for (const r of filtered) {
      const key = r.academic_term_id
      const name = r.academic_term?.name ?? "Unscheduled"
      const start = r.academic_term?.start_date ?? ""
      if (!map.has(key)) map.set(key, { name, start, items: [] })
      map.get(key)!.items.push(r)
    }
    return Array.from(map.entries()).sort((a, b) => a[1].start.localeCompare(b[1].start))
  }, [filtered])

  /**
   * Generate the billing rows for every school contract in this department.
   *
   * `generate_term_billings` is idempotent and refuses to touch a row that has
   * already been invoiced or paid, so this is safe to press repeatedly — it
   * creates what is missing and refreshes bus counts on still-pending terms.
   * That is how adding a seventh bus mid-contract reaches the NEXT unbilled
   * term without re-billing a term the school has already settled.
   */
  async function generateAll() {
    if (!department?.id) return
    setGenerating(true)
    try {
      const supabase = createClient()
      const { data: sales, error } = await supabase
        .from("sales")
        .select("id")
        .eq("department_id", department.id)
      if (error) throw error

      const ids = (sales ?? []).map((s) => (s as { id: string }).id)
      if (ids.length === 0) {
        toast.info("No school contracts to generate billings for yet.")
        return
      }

      let created = 0
      let refreshed = 0
      let unconfigured = false
      for (const id of ids) {
        const { data, error: rpcErr } = await supabase.rpc("generate_term_billings", {
          p_sale_id: id,
        })
        if (rpcErr) {
          console.error(rpcErr)
          continue
        }
        const r = data as unknown as {
          ok: boolean; reason?: string; created?: number; refreshed?: number
        }
        if (!r?.ok && r?.reason === "term_calendar_not_configured") unconfigured = true
        created += r?.created ?? 0
        refreshed += r?.refreshed ?? 0
      }

      if (unconfigured) {
        toast.warning("Term calendar is not configured — nothing could be generated.")
      } else {
        toast.success(`${created} billing row(s) created, ${refreshed} refreshed.`)
      }
      await load()
    } catch (err) {
      console.error(err)
      toast.error("Could not generate term billings")
    } finally {
      setGenerating(false)
    }
  }

  async function setStatus(row: BillingRow, status: InvoiceStatus) {
    const supabase = createClient()
    const previous = rows
    const paidDate = status === "paid" ? new Date().toISOString().slice(0, 10) : null
    setRows((prev) =>
      prev.map((r) =>
        r.id === row.id ? { ...r, invoice_status: status, paid_date: paidDate ?? r.paid_date } : r,
      ),
    )
    const { error } = await supabase
      .from("term_billings")
      .update({ invoice_status: status, ...(paidDate ? { paid_date: paidDate } : {}) })
      .eq("id", row.id)

    if (error) {
      console.error(error)
      setRows(previous)
      toast.error("Could not update the billing")
    } else {
      toast.success(`Marked ${status}`)
    }
  }

  if (!department) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] gap-3 text-center p-6">
        <div className="flex h-14 w-14 items-center justify-center rounded-full bg-slate-100">
          <Users className="h-7 w-7 text-slate-400" />
        </div>
        <h2 className="text-lg font-semibold text-slate-800">No department selected</h2>
        <p className="text-sm text-slate-500 max-w-xs">
          Term billing belongs to the School Bus department.
        </p>
      </div>
    )
  }

  return (
    <div className="p-4 lg:p-6 space-y-4">
      <div className="flex items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Term Billing</h1>
          <p className="text-slate-500 text-sm mt-0.5">
            {loading ? "Loading…" : `${filtered.length} of ${rows.length} billings`} ·{" "}
            {department.name}
          </p>
        </div>
        <Button
          variant="outline"
          className="gap-1.5"
          onClick={() => void generateAll()}
          disabled={generating || !calendarReady}
          title={calendarReady ? undefined : "Configure the term calendar first"}
        >
          {generating ? (
            <Loader2 className="h-4 w-4 animate-spin" />
          ) : (
            <RefreshCw className="h-4 w-4" />
          )}
          Generate Billings
        </Button>
      </div>

      {/* Term calendar state — the page must be honest when it is not set up. */}
      {!calendarReady ? (
        <div className="rounded-lg border border-amber-200 bg-amber-50 p-4">
          <p className="flex items-center gap-2 font-medium text-amber-900">
            <CalendarX2 className="h-4 w-4" />
            Term calendar not configured
          </p>
          <p className="text-sm text-amber-800 mt-1">
            No academic terms have been entered yet, so term billings cannot be generated and
            no holiday awareness is active. Add the real term and holiday dates in{" "}
            <Link href="/admin" className="underline font-medium">Admin → Departments</Link>.
          </p>
        </div>
      ) : (
        <div className="flex flex-wrap gap-3 text-sm">
          <div className="rounded-lg border border-slate-200 px-3 py-2">
            <span className="text-slate-500">Current term: </span>
            <span className="font-medium text-slate-800">{thisTerm?.name ?? "Holiday"}</span>
          </div>
          {upcoming && daysToNext !== null && (
            <div className="rounded-lg border border-slate-200 px-3 py-2">
              <span className="text-slate-500">{upcoming.name} starts in </span>
              <span className="font-medium text-slate-800">{daysToNext} days</span>
            </div>
          )}
        </div>
      )}

      {/* Filters */}
      <div className="flex flex-wrap gap-2">
        <select
          value={termFilter}
          onChange={(e) => setTermFilter(e.target.value)}
          className="h-9 rounded-md border border-input bg-background px-3 text-sm text-slate-700"
        >
          <option value="">All terms</option>
          {academicTerms.map((t) => (
            <option key={t.id} value={t.id}>{t.name}</option>
          ))}
        </select>
        <select
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value)}
          className="h-9 rounded-md border border-input bg-background px-3 text-sm text-slate-700"
        >
          <option value="">All statuses</option>
          {Object.keys(STATUS_CLASSES).map((s) => (
            <option key={s} value={s} className="capitalize">{s}</option>
          ))}
        </select>
      </div>

      {loading ? (
        <div className="space-y-2">
          {Array.from({ length: 4 }).map((_, i) => (
            <Skeleton key={i} className="h-10 w-full" />
          ))}
        </div>
      ) : grouped.length === 0 ? (
        <div className="rounded-lg border border-slate-200 py-12 text-center">
          <CalendarClock className="h-8 w-8 text-slate-300 mx-auto mb-2" />
          <p className="text-sm text-slate-500">
            {rows.length === 0
              ? "No term billings yet. They are generated when a school's contract is saved."
              : "No billings match these filters."}
          </p>
        </div>
      ) : (
        grouped.map(([termId, group]) => (
          <div key={termId} className="rounded-lg border border-slate-200 overflow-hidden">
            <div className="bg-slate-50 px-3 py-2 border-b border-slate-200 flex items-center gap-2">
              <CalendarClock className="h-4 w-4 text-indigo-500" />
              <span className="font-medium text-slate-800 text-sm">{group.name}</span>
              <span className="text-xs text-slate-500">
                {group.items.length} school{group.items.length === 1 ? "" : "s"} ·{" "}
                {formatKes(
                  group.items.reduce((sum, r) => sum + (r.total_amount ?? 0), 0),
                )}
              </span>
            </div>
            <table className="w-full text-sm">
              <thead className="text-slate-600">
                <tr>
                  <th className="text-left font-medium px-3 py-2">School</th>
                  <th className="text-right font-medium px-3 py-2">Buses</th>
                  <th className="text-right font-medium px-3 py-2">Amount</th>
                  <th className="text-left font-medium px-3 py-2">Due</th>
                  <th className="text-left font-medium px-3 py-2">Status</th>
                  <th className="px-3 py-2" />
                </tr>
              </thead>
              <tbody>
                {group.items.map((r) => {
                  const days = r.due_date ? daysUntil(r.due_date) : null
                  const unpaid = !["paid", "waived"].includes(r.invoice_status)
                  return (
                    <tr key={r.id} className="border-t border-slate-100 hover:bg-slate-50">
                      <td className="px-3 py-2">
                        <Link
                          href={`/leads/${r.lead_id}`}
                          className="font-medium text-slate-800 hover:text-blue-600 hover:underline"
                        >
                          {schoolName(r.lead)}
                        </Link>
                      </td>
                      <td className="px-3 py-2 text-right text-slate-600">{r.bus_count}</td>
                      <td className="px-3 py-2 text-right text-slate-700 whitespace-nowrap">
                        {formatKes(r.total_amount, r.currency)}
                      </td>
                      <td className="px-3 py-2 whitespace-nowrap">
                        {r.due_date ? (
                          <span
                            className={cn(
                              "font-medium",
                              unpaid && days !== null ? getRenewalColorClass(days) : "text-slate-500",
                            )}
                          >
                            {formatDate(r.due_date)}
                            {unpaid && days !== null && days < 0 && (
                              <span className="text-xs ml-1">({Math.abs(days)}d overdue)</span>
                            )}
                          </span>
                        ) : (
                          <span className="text-slate-400">—</span>
                        )}
                      </td>
                      <td className="px-3 py-2">
                        <span
                          className={cn(
                            "inline-flex rounded-full border px-2 py-0.5 text-xs font-medium capitalize",
                            STATUS_CLASSES[r.invoice_status],
                          )}
                        >
                          {r.invoice_status}
                        </span>
                      </td>
                      <td className="px-3 py-2">
                        <div className="flex gap-1 justify-end">
                          {r.invoice_status === "pending" && (
                            <Button
                              size="sm" variant="outline" className="h-7 px-2 text-xs gap-1"
                              onClick={() => void setStatus(r, "invoiced")}
                            >
                              <FileText className="h-3 w-3" /> Invoiced
                            </Button>
                          )}
                          {unpaid && (
                            <Button
                              size="sm" variant="outline" className="h-7 px-2 text-xs gap-1"
                              onClick={() => void setStatus(r, "paid")}
                            >
                              <Check className="h-3 w-3" /> Paid
                            </Button>
                          )}
                          {unpaid && (
                            <Button
                              size="sm" variant="ghost" className="h-7 px-2 text-xs text-slate-500"
                              title="Waive"
                              onClick={() => void setStatus(r, "waived")}
                            >
                              <Ban className="h-3 w-3" />
                            </Button>
                          )}
                        </div>
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        ))
      )}
    </div>
  )
}
